# https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
spec:
  # namespace: scratch
  selector:
    matchLabels:
      app: mynginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx0
        image: nginx:1.21.3-alpine
        ports:
        - containerPort: 80

