# https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  # namespace: scratch
  selector:
    matchLabels:
      app: my-nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.21.3-alpine
        ports:
        - containerPort: 80

